Repository 9oormthonUNIV-Halpme/Backend, pull requests merged in 2025-05, with the labels that each got.

#14 Refactor Member and Post entities
  src/main/java/com/core/halpme/api/members/entity/Gender.java
  src/main/java/com/core/halpme/api/members/entity/Member.java
  src/main/java/com/core/halpme/api/members/entity/MemberType.java
  src/main/java/com/core/halpme/api/members/entity/Role.java
  src/main/java/com/core/halpme/api/members/entity/User.java
  src/main/java/com/core/halpme/api/post/entity/ActivityStatus.java
  src/main/java/com/core/halpme/api/post/entity/Post.java
  src/main/java/com/core/halpme/api/post/entity/PostMemberType.java
  src/main/java/com/core/halpme/domain/Activity.java
  src/main/java/com/core/halpme/domain/Requester.java
  src/main/java/com/core/halpme/domain/VolunteerCertification.java
  src/main/resources/application.yml
Labels: refactor, 김현빈

#16 Login register/#6
  .gitignore
  build.gradle
  src/main/java/com/core/halpme/api/members/controller/MemberController.java
  src/main/java/com/core/halpme/api/members/dto/LoginRequest.java
  src/main/java/com/core/halpme/api/members/dto/RegisterRequest.java
  src/main/java/com/core/halpme/api/members/entity/Address.java
  src/main/java/com/core/halpme/api/members/jwt/JwtAuthenticationFilter.java
  src/main/java/com/core/halpme/api/members/jwt/JwtTokenProvider.java
  src/main/java/com/core/halpme/api/members/repository/MemberRepository.java
  src/main/java/com/core/halpme/api/members/service/MemberService.java
  src/main/java/com/core/halpme/common/advice/GlobalExceptionHandler.java
  src/main/java/com/core/halpme/common/config/CorsConfig.java
  src/main/java/com/core/halpme/common/config/SecurityConfig.java
  src/main/java/com/core/halpme/common/config/SwaggerConfig.java
  src/main/java/com/core/halpme/common/response/ErrorStatus.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
  src/main/resources/application.yml
Labels: fix, refactor

#20 [FEAT] 커스텀 예외 추가 및 글로벌 예외 핸들러 리팩토링
  src/main/java/com/core/halpme/api/members/controller/MemberController.java
  src/main/java/com/core/halpme/common/advice/GlobalExceptionHandler.java
  src/main/java/com/core/halpme/common/exception/BadRequestException.java
  src/main/java/com/core/halpme/common/exception/ConflictException.java
  src/main/java/com/core/halpme/common/exception/ForbiddenException.java
  src/main/java/com/core/halpme/common/exception/InternalServerException.java
  src/main/java/com/core/halpme/common/exception/NotFoundException.java
  src/main/java/com/core/halpme/common/exception/UnauthorizedException.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: feat, refactor, 김현빈

#22 [REFACTOR] Address 생성자 파라미터 매칭 에러 수정
  src/main/java/com/core/halpme/api/members/entity/Address.java
  src/main/java/com/core/halpme/api/post/service/PostService.java
Labels: fix, 김현빈

#26 [FIX] 스웨거 경로 수정
  src/main/java/com/core/halpme/TestController.java
  src/main/java/com/core/halpme/common/config/SecurityConfig.java
Labels: fix, 김현빈

#32 [Feat] mypage, participation 추가
  logs/halpme.log.2025-05-21.0.gz
  logs/halpme.log.2025-05-23.0.gz
  src/main/java/com/core/halpme/api/members/controller/MemberController.java
  src/main/java/com/core/halpme/api/members/dto/LoginRequestDto.java
  src/main/java/com/core/halpme/api/members/dto/RegisterRequestDto.java
  src/main/java/com/core/halpme/api/members/entity/Address.java
  src/main/java/com/core/halpme/api/members/entity/Member.java
  src/main/java/com/core/halpme/api/members/entity/Role.java
  src/main/java/com/core/halpme/api/members/service/MemberService.java
  src/main/java/com/core/halpme/api/mypage/controller/MyPageController.java
  src/main/java/com/core/halpme/api/mypage/dto/MyPageResponseDto.java
  src/main/java/com/core/halpme/api/mypage/dto/MyParticipationDto.java
  src/main/java/com/core/halpme/api/mypage/dto/MyPostDto.java
  src/main/java/com/core/halpme/api/mypage/service/MyPageService.java
  src/main/java/com/core/halpme/api/participation/controller/ParticipationController.java
  src/main/java/com/core/halpme/api/participation/dto/ParticipationRequestDto.java
  src/main/java/com/core/halpme/api/participation/dto/ParticipationResponseDto.java
  src/main/java/com/core/halpme/api/participation/entity/Participation.java
  src/main/java/com/core/halpme/api/participation/entity/ParticipationStatus.java
  src/main/java/com/core/halpme/api/participation/repository/ParticipationRepository.java
  src/main/java/com/core/halpme/api/participation/service/ParticipationService.java
  src/main/java/com/core/halpme/api/post/controller/PostController.java
  src/main/java/com/core/halpme/api/post/dto/PostCreateRequest.java
  src/main/java/com/core/halpme/api/post/dto/PostResponse.java
  src/main/java/com/core/halpme/api/post/entity/Post.java
  src/main/java/com/core/halpme/api/post/service/PostService.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: feat, 박승준

#36 Chatting/#12
  src/main/java/com/core/halpme/api/chat/controller/ChatMessageController.java
  src/main/java/com/core/halpme/api/chat/dto/ChatMessageDto.java
  src/main/java/com/core/halpme/api/chat/dto/ChatRoomDto.java
  src/main/java/com/core/halpme/api/chat/entity/ChatRoom.java
  src/main/java/com/core/halpme/api/chat/repository/MessageReadStatusRepository.java
  src/main/java/com/core/halpme/api/chat/service/ChatRoomServiceImpl.java
Labels: bug, fix

#42 [FEAT] AWS S3 도입
  .github/workflows/CI.yml
  src/main/java/com/core/halpme/api/HealthCheckController.java
  src/main/java/com/core/halpme/api/aws/s3/controller/S3Controller.java
  src/main/java/com/core/halpme/api/aws/s3/service/S3Service.java
  src/main/java/com/core/halpme/api/chat/controller/ChatMessageController.java
  src/main/java/com/core/halpme/api/chat/dto/ChatMessageDto.java
  src/main/java/com/core/halpme/api/chat/entity/ChatMessage.java
  src/main/java/com/core/halpme/api/chat/entity/ChatMessageImage.java
  src/main/java/com/core/halpme/api/chat/entity/MessageType.java
  src/main/java/com/core/halpme/api/chat/repository/ChatMessageImageRepository.java
  src/main/java/com/core/halpme/api/chat/service/ChatMessageServiceImpl.java
  src/main/java/com/core/halpme/api/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/core/halpme/api/members/entity/Member.java
  src/main/java/com/core/halpme/api/post/entity/PostImage.java
  src/main/java/com/core/halpme/common/config/S3Config.java
  src/main/java/com/core/halpme/common/config/SwaggerConfig.java
  src/main/java/com/core/halpme/common/response/ErrorStatus.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: feat, 김현빈

#48 Feat/#45 update profile
  src/main/java/com/core/halpme/api/members/controller/MemberController.java
  src/main/java/com/core/halpme/api/members/dto/UpdateMemberRequestDto.java
  src/main/java/com/core/halpme/api/members/entity/Member.java
  src/main/java/com/core/halpme/api/members/service/MemberService.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: fix, feat

#51 Refact/#50 chatting nickname
  src/main/java/com/core/halpme/api/chat/controller/ChatRoomController.java
  src/main/java/com/core/halpme/api/chat/dto/ChatRoomDto.java
  src/main/java/com/core/halpme/api/chat/dto/OpponentNicknameDto.java
  src/main/java/com/core/halpme/api/chat/service/ChatRoomService.java
  src/main/java/com/core/halpme/api/chat/service/ChatRoomServiceImpl.java
  src/main/java/com/core/halpme/common/response/ErrorStatus.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: refactor, 양우현

#49 [FEAT] rank 파일 수정 및 post디렉토리 poststatus 변환 로직 추가
  src/main/java/com/core/halpme/api/members/entity/Member.java
  src/main/java/com/core/halpme/api/post/controller/PostController.java
  src/main/java/com/core/halpme/api/post/dto/MyPostListResponseDto.java
  src/main/java/com/core/halpme/api/post/dto/MyVolunteerPostListResponseDto.java
  src/main/java/com/core/halpme/api/post/dto/PostCreateRequestDto.java
  src/main/java/com/core/halpme/api/post/dto/PostDetailResponseDto.java
  src/main/java/com/core/halpme/api/post/dto/PostTotalListResponseDto.java
  src/main/java/com/core/halpme/api/post/entity/Post.java
  src/main/java/com/core/halpme/api/post/entity/PostStatus.java
  src/main/java/com/core/halpme/api/post/service/PostService.java
  src/main/java/com/core/halpme/api/rank/controller/RankController.java
  src/main/java/com/core/halpme/api/rank/dto/RankResponseDto.java
  src/main/java/com/core/halpme/api/rank/entity/Rank.java
  src/main/java/com/core/halpme/api/rank/entity/RankLevel.java
  src/main/java/com/core/halpme/api/rank/repository/RankRepository.java
  src/main/java/com/core/halpme/api/rank/service/RankService.java
  src/main/java/com/core/halpme/common/response/SuccessStatus.java
Labels: feat, 박승준
